language: c++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build; cmake ../c_src
  - cd build; make

notifications:
  email: false
