language: c++

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build; cmake ../c_src
  - cd build; make

notifications:
  email: false
